# Generated by Django 4.0.4 on 2022-10-10 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_receiptvoucher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentvoucher',
            name='particulars',
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='amount1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='amount2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='amount3',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='amount4',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='amount5',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='amount6',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='amount7',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='amount8',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='particulars1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='particulars2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='particulars3',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='particulars4',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='particulars5',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='particulars6',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='particulars7',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='particulars8',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
