# Generated by Django 4.0.4 on 2022-10-10 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_remove_paymentvoucher_particulars_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receiptvoucher',
            name='particulars',
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='accountname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='currentbalance',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='dr_cr',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='dr_cr1',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='dr_cr2',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='dr_cr3',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='dr_cr4',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='dr_cr5',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='dr_cr6',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='dr_cr7',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='dr_cr8',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='receiptvoucher',
            name='accountname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='receiptvoucher',
            name='amount1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='receiptvoucher',
            name='amount2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='receiptvoucher',
            name='amount3',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='receiptvoucher',
            name='amount4',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='receiptvoucher',
            name='amount5',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='receiptvoucher',
            name='amount6',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='receiptvoucher',
            name='amount7',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='receiptvoucher',
            name='amount8',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='receiptvoucher',
            name='currentbalance',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='receiptvoucher',
            name='dr_cr',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='receiptvoucher',
            name='dr_cr1',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='receiptvoucher',
            name='dr_cr2',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='receiptvoucher',
            name='dr_cr3',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='receiptvoucher',
            name='dr_cr4',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='receiptvoucher',
            name='dr_cr5',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='receiptvoucher',
            name='dr_cr6',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='receiptvoucher',
            name='dr_cr7',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='receiptvoucher',
            name='dr_cr8',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='receiptvoucher',
            name='particulars1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='receiptvoucher',
            name='particulars2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='receiptvoucher',
            name='particulars3',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='receiptvoucher',
            name='particulars4',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='receiptvoucher',
            name='particulars5',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='receiptvoucher',
            name='particulars6',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='receiptvoucher',
            name='particulars7',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='receiptvoucher',
            name='particulars8',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
