# Generated by Django 4.0.4 on 2022-10-11 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_paymentvoucher_curbalance1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentvoucher',
            name='curbalance2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
