# Generated by Django 4.0.4 on 2022-10-11 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_alter_receiptvoucher_curbalance2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptvoucher',
            name='amount2',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
