# Generated by Django 4.0.4 on 2022-10-11 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_alter_receiptvoucher_amount2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptvoucher',
            name='amount3',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='receiptvoucher',
            name='amount4',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='receiptvoucher',
            name='amount5',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='receiptvoucher',
            name='curbalance3',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='receiptvoucher',
            name='curbalance4',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='receiptvoucher',
            name='curbalance5',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
