# Generated by Django 4.0.4 on 2022-10-13 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_alter_receiptvoucher_amount3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentvoucher',
            name='amount2',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='amount3',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='amount4',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='amount5',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='curbalance2',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='curbalance3',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='curbalance4',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='curbalance5',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.CreateModel(
            name='receiptdetails_creditnote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_no', models.CharField(max_length=225)),
                ('dispatch_Doc_No', models.CharField(max_length=225)),
                ('dispatch_through', models.CharField(max_length=225)),
                ('destination', models.CharField(max_length=225)),
                ('carrier_name', models.CharField(max_length=225)),
                ('bill_of_lading_no', models.CharField(max_length=225)),
                ('date', models.DateField()),
                ('motorvehicle_no', models.CharField(max_length=225)),
                ('original_invoice_no', models.CharField(max_length=225)),
                ('invoice_date', models.DateField()),
                ('ledger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.ledger')),
                ('voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.voucher')),
            ],
        ),
    ]
