# Generated by Django 4.0.4 on 2022-10-13 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_alter_paymentvoucher_amount2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='partydetails_creditnote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=255)),
                ('mailing_address', models.CharField(max_length=255)),
                ('Address', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
            ],
        ),
    ]
