# Generated by Django 4.0.4 on 2022-10-14 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_partydetails_creditnote'),
    ]

    operations = [
        migrations.CreateModel(
            name='creditnote_voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('partyname', models.CharField(max_length=255, null=True)),
                ('currentbalance', models.IntegerField(null=True)),
                ('dr_cr', models.CharField(max_length=10, null=True)),
                ('ledgeraccount', models.CharField(max_length=255, null=True)),
                ('curbalance1', models.IntegerField(null=True)),
                ('dr_cr1', models.CharField(max_length=10, null=True)),
                ('vouchertype', models.CharField(max_length=255)),
                ('voucherno', models.IntegerField()),
                ('debitamount', models.IntegerField(null=True)),
                ('creditamount', models.IntegerField(null=True)),
                ('item1', models.CharField(default=True, max_length=225)),
                ('quantity1', models.IntegerField(null=True)),
                ('rate1', models.IntegerField(null=True)),
                ('amount1', models.IntegerField(null=True)),
                ('narration', models.CharField(default=True, max_length=225)),
            ],
        ),
    ]
