# Generated by Django 4.0.4 on 2022-10-14 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_creditnote_voucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnote_voucher',
            name='per1',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
