# Generated by Django 4.0.4 on 2022-10-14 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_creditnote_voucher_per1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_itemcreation',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
